import 'package:flutter/material.dart';

class IconList extends StatelessWidget {

  final Widget iconListElement = GridView.count(
    crossAxisCount: 3,
    childAspectRatio: 2.0,
    mainAxisSpacing: 10.0,
    children: <Widget>[
      Column(children: <Widget>[ Icon(Icons.ac_unit), Text('ac_unit') ],),
      Column(children: <Widget>[ Icon(Icons.access_alarm), Text('access_alarm') ],),
      Column(children: <Widget>[ Icon(Icons.access_alarms), Text('access_alarms') ],),
      Column(children: <Widget>[ Icon(Icons.access_time), Text('access_time') ],),
      Column(children: <Widget>[ Icon(Icons.accessibility), Text('accessibility') ],),
      Column(children: <Widget>[ Icon(Icons.accessibility_new), Text('accessibility_new') ],),

      Column(children: <Widget>[ Icon(Icons.accessible), Text('accessible') ],),
      Column(children: <Widget>[ Icon(Icons.accessible_forward), Text('accessible_forward') ],),
      Column(children: <Widget>[ Icon(Icons.account_balance), Text('account_balance') ],),
      Column(children: <Widget>[ Icon(Icons.account_balance_wallet), Text('account_balance_wallet') ],),
      Column(children: <Widget>[ Icon(Icons.account_box), Text('account_box') ],),
      Column(children: <Widget>[ Icon(Icons.account_circle), Text('account_circle') ],),

      Column(children: <Widget>[ Icon(Icons.adb), Text('adb') ],),
      Column(children: <Widget>[ Icon(Icons.add), Text('add') ],),
      Column(children: <Widget>[ Icon(Icons.add_a_photo), Text('add_a_photo') ],),
      Column(children: <Widget>[ Icon(Icons.add_alarm), Text('add_alarm') ],),
      Column(children: <Widget>[ Icon(Icons.add_alert), Text('add_alert') ],),
      Column(children: <Widget>[ Icon(Icons.add_box), Text('add_box') ],),

      Column(children: <Widget>[ Icon(Icons.add_call), Text('add_call') ],),
      Column(children: <Widget>[ Icon(Icons.add_circle), Text('add_circle') ],),
      Column(children: <Widget>[ Icon(Icons.add_circle_outline), Text('add_circle_outline') ],),
      Column(children: <Widget>[ Icon(Icons.add_comment), Text('add_comment') ],),
      Column(children: <Widget>[ Icon(Icons.add_location), Text('add_location') ],),
      Column(children: <Widget>[ Icon(Icons.add_photo_alternate), Text('add_photo_alternate') ],),

      Column(children: <Widget>[ Icon(Icons.add_shopping_cart), Text('add_shopping_cart') ],),
      Column(children: <Widget>[ Icon(Icons.add_to_home_screen), Text('add_to_home_screen') ],),
      Column(children: <Widget>[ Icon(Icons.add_to_photos), Text('add_to_photos') ],),
      Column(children: <Widget>[ Icon(Icons.add_to_queue), Text('add_to_queue') ],),
      Column(children: <Widget>[ Icon(Icons.adjust), Text('adjust') ],),
      Column(children: <Widget>[ Icon(Icons.airline_seat_flat), Text('airline_seat_flat') ],),

      Column(children: <Widget>[ Icon(Icons.airline_seat_flat_angled), Text('airline_seat_flat_angled') ],),
      Column(children: <Widget>[ Icon(Icons.airline_seat_individual_suite), Text('airline_seat_individual_suite') ],),
      Column(children: <Widget>[ Icon(Icons.airline_seat_legroom_extra), Text('airline_seat_legroom_extra') ],),
      Column(children: <Widget>[ Icon(Icons.airline_seat_legroom_normal), Text('airline_seat_legroom_normal') ],),
      Column(children: <Widget>[ Icon(Icons.airline_seat_legroom_reduced), Text('airline_seat_legroom_reduced') ],),
      Column(children: <Widget>[ Icon(Icons.airplanemode_active), Text('airplanemode_active') ],),

      Column(children: <Widget>[ Icon(Icons.airplanemode_inactive), Text('airplanemode_inactive') ],),
      Column(children: <Widget>[ Icon(Icons.airplay), Text('airplay') ],),
      Column(children: <Widget>[ Icon(Icons.airport_shuttle), Text('airport_shuttle') ],),
      Column(children: <Widget>[ Icon(Icons.alarm), Text('alarm') ],),
      Column(children: <Widget>[ Icon(Icons.alarm_add), Text('alarm_add') ],),
      Column(children: <Widget>[ Icon(Icons.alarm_off), Text('alarm_off') ],),

      Column(children: <Widget>[ Icon(Icons.alarm_on), Text('alarm_on') ],),
      Column(children: <Widget>[ Icon(Icons.album), Text('album') ],),
      Column(children: <Widget>[ Icon(Icons.all_inclusive), Text('all_inclusive') ],),
      Column(children: <Widget>[ Icon(Icons.all_out), Text('all_out') ],),
      Column(children: <Widget>[ Icon(Icons.alternate_email), Text('alternate_email') ],),
      Column(children: <Widget>[ Icon(Icons.android), Text('android') ],),

      Column(children: <Widget>[ Icon(Icons.announcement), Text('announcement') ],),
      Column(children: <Widget>[ Icon(Icons.apps), Text('apps') ],),
      Column(children: <Widget>[ Icon(Icons.archive), Text('archive') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_back), Text('arrow_back') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_back_ios), Text('arrow_back_ios') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_downward), Text('arrow_downward') ],),

      Column(children: <Widget>[ Icon(Icons.arrow_drop_down), Text('arrow_drop_down') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_drop_down_circle), Text('arrow_drop_down_circle') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_drop_up), Text('arrow_drop_up') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_forward), Text('arrow_forward') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_forward_ios), Text('arrow_forward_ios') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_left), Text('arrow_left') ],),

      Column(children: <Widget>[ Icon(Icons.arrow_right), Text('arrow_right') ],),
      Column(children: <Widget>[ Icon(Icons.arrow_upward), Text('arrow_upward') ],),
      Column(children: <Widget>[ Icon(Icons.art_track), Text('art_track') ],),
      Column(children: <Widget>[ Icon(Icons.aspect_ratio), Text('aspect_ratio') ],),
      Column(children: <Widget>[ Icon(Icons.assessment), Text('assessment') ],),
      Column(children: <Widget>[ Icon(Icons.assignment), Text('assignment') ],),

      Column(children: <Widget>[ Icon(Icons.assignment_ind), Text('assignment_ind') ],),
      Column(children: <Widget>[ Icon(Icons.assignment_late), Text('assignment_late') ],),
      Column(children: <Widget>[ Icon(Icons.assignment_return), Text('assignment_return') ],),
      Column(children: <Widget>[ Icon(Icons.assignment_returned), Text('assignment_returned') ],),
      Column(children: <Widget>[ Icon(Icons.assignment_turned_in), Text('assignment_turned_in') ],),
      Column(children: <Widget>[ Icon(Icons.assistant), Text('assistant') ],),

      Column(children: <Widget>[ Icon(Icons.assistant_photo), Text('assignment_ind') ],),
      Column(children: <Widget>[ Icon(Icons.atm), Text('atm') ],),
      Column(children: <Widget>[ Icon(Icons.attach_file), Text('attach_file') ],),
      Column(children: <Widget>[ Icon(Icons.attach_money), Text('attach_money') ],),
      Column(children: <Widget>[ Icon(Icons.attachment), Text('attachment') ],),
      Column(children: <Widget>[ Icon(Icons.audiotrack), Text('audiotrack') ],),

      Column(children: <Widget>[ Icon(Icons.autorenew), Text('autorenew') ],),
      Column(children: <Widget>[ Icon(Icons.av_timer), Text('av_timer') ],),
      Column(children: <Widget>[ Icon(Icons.backspace), Text('backspace') ],),
      Column(children: <Widget>[ Icon(Icons.backup), Text('backup') ],),
      Column(children: <Widget>[ Icon(Icons.battery_alert), Text('battery_alert') ],),
      Column(children: <Widget>[ Icon(Icons.battery_charging_full), Text('battery_charging_full') ],),

      Column(children: <Widget>[ Icon(Icons.battery_full), Text('battery_full') ],),
      Column(children: <Widget>[ Icon(Icons.battery_std), Text('battery_std') ],),
      Column(children: <Widget>[ Icon(Icons.battery_unknown), Text('battery_unknown') ],),
      Column(children: <Widget>[ Icon(Icons.beach_access), Text('beach_access') ],),
      Column(children: <Widget>[ Icon(Icons.beenhere), Text('beenhere') ],),
      Column(children: <Widget>[ Icon(Icons.block), Text('block') ],),

      Column(children: <Widget>[ Icon(Icons.bluetooth), Text('bluetooth') ],),
      Column(children: <Widget>[ Icon(Icons.bluetooth_audio), Text('bluetooth_audio') ],),
      Column(children: <Widget>[ Icon(Icons.bluetooth_connected), Text('bluetooth_connected') ],),
      Column(children: <Widget>[ Icon(Icons.bluetooth_disabled), Text('bluetooth_disabled') ],),
      Column(children: <Widget>[ Icon(Icons.bluetooth_searching), Text('bluetooth_searching') ],),
      Column(children: <Widget>[ Icon(Icons.blur_circular), Text('blur_circular') ],),

      Column(children: <Widget>[ Icon(Icons.blur_linear), Text('blur_linear') ],),
      Column(children: <Widget>[ Icon(Icons.blur_off), Text('blur_off') ],),
      Column(children: <Widget>[ Icon(Icons.blur_on), Text('blur_on') ],),
      Column(children: <Widget>[ Icon(Icons.book), Text('book') ],),
      Column(children: <Widget>[ Icon(Icons.bookmark), Text('bookmark') ],),
      Column(children: <Widget>[ Icon(Icons.bookmark_border), Text('bookmark_border') ],),

      Column(children: <Widget>[ Icon(Icons.border_all), Text('border_all') ],),
      Column(children: <Widget>[ Icon(Icons.border_bottom), Text('border_bottom') ],),
      Column(children: <Widget>[ Icon(Icons.border_clear), Text('border_clear') ],),
      Column(children: <Widget>[ Icon(Icons.border_color), Text('border_color') ],),
      Column(children: <Widget>[ Icon(Icons.border_horizontal), Text('border_horizontal') ],),
      Column(children: <Widget>[ Icon(Icons.border_inner), Text('border_inner') ],),

      Column(children: <Widget>[ Icon(Icons.border_left), Text('border_left') ],),
      Column(children: <Widget>[ Icon(Icons.border_outer), Text('border_outer') ],),
      Column(children: <Widget>[ Icon(Icons.border_right), Text('border_right') ],),
      Column(children: <Widget>[ Icon(Icons.border_style), Text('border_style') ],),
      Column(children: <Widget>[ Icon(Icons.border_top), Text('border_top') ],),
      Column(children: <Widget>[ Icon(Icons.border_vertical), Text('border_vertical') ],),

      Column(children: <Widget>[ Icon(Icons.branding_watermark), Text('branding_watermark') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_1), Text('brightness_1') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_2), Text('brightness_2') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_3), Text('brightness_3') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_4), Text('brightness_4') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_5), Text('brightness_5') ],),

      Column(children: <Widget>[ Icon(Icons.brightness_6), Text('brightness_6') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_7), Text('brightness_7') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_auto), Text('brightness_auto') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_high), Text('brightness_high') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_low), Text('brightness_low') ],),
      Column(children: <Widget>[ Icon(Icons.brightness_medium), Text('brightness_medium') ],),

      Column(children: <Widget>[ Icon(Icons.broken_image), Text('broken_image') ],),
      Column(children: <Widget>[ Icon(Icons.brush), Text('brush') ],),
      Column(children: <Widget>[ Icon(Icons.bubble_chart), Text('bubble_chart') ],),
      Column(children: <Widget>[ Icon(Icons.bug_report), Text('bug_report') ],),
      Column(children: <Widget>[ Icon(Icons.build), Text('build') ],),
      Column(children: <Widget>[ Icon(Icons.burst_mode), Text('burst_mode') ],),

      Column(children: <Widget>[ Icon(Icons.business), Text('business') ],),
      Column(children: <Widget>[ Icon(Icons.business_center), Text('business_center') ],),
      Column(children: <Widget>[ Icon(Icons.cached), Text('cached') ],),
      Column(children: <Widget>[ Icon(Icons.cake), Text('cake') ],),
      Column(children: <Widget>[ Icon(Icons.calendar_today), Text('calendar_today') ],),
      Column(children: <Widget>[ Icon(Icons.calendar_view_day), Text('calendar_view_day') ],),

      Column(children: <Widget>[ Icon(Icons.call), Text('call') ],),
      Column(children: <Widget>[ Icon(Icons.call_end), Text('call_end') ],),
      Column(children: <Widget>[ Icon(Icons.call_made), Text('call_made') ],),
      Column(children: <Widget>[ Icon(Icons.call_merge), Text('call_merge') ],),
      Column(children: <Widget>[ Icon(Icons.call_missed), Text('call_missed') ],),
      Column(children: <Widget>[ Icon(Icons.call_missed_outgoing), Text('call_missed_outgoing') ],),

      Column(children: <Widget>[ Icon(Icons.call_received), Text('call_received') ],),
      Column(children: <Widget>[ Icon(Icons.call_split), Text('call_split') ],),
      Column(children: <Widget>[ Icon(Icons.call_to_action), Text('call_to_action') ],),
      Column(children: <Widget>[ Icon(Icons.camera), Text('camera') ],),
      Column(children: <Widget>[ Icon(Icons.camera_alt), Text('camera_alt') ],),
      Column(children: <Widget>[ Icon(Icons.camera_enhance), Text('camera_enhance') ],),

      Column(children: <Widget>[ Icon(Icons.camera_front), Text('camera_front') ],),
      Column(children: <Widget>[ Icon(Icons.camera_rear), Text('camera_rear') ],),
      Column(children: <Widget>[ Icon(Icons.camera_roll), Text('camera_roll') ],),
      Column(children: <Widget>[ Icon(Icons.cancel), Text('cancel') ],),
      Column(children: <Widget>[ Icon(Icons.card_giftcard), Text('card_giftcard') ],),
      Column(children: <Widget>[ Icon(Icons.card_membership), Text('card_membership') ],),

      Column(children: <Widget>[ Icon(Icons.card_travel), Text('card_travel') ],),
      Column(children: <Widget>[ Icon(Icons.casino), Text('casino') ],),
      Column(children: <Widget>[ Icon(Icons.cast), Text('cast') ],),
      Column(children: <Widget>[ Icon(Icons.cast_connected), Text('cast_connected') ],),
      Column(children: <Widget>[ Icon(Icons.category), Text('category') ],),
      Column(children: <Widget>[ Icon(Icons.center_focus_strong), Text('center_focus_strong') ],),

      Column(children: <Widget>[ Icon(Icons.center_focus_weak), Text('center_focus_weak') ],),
      Column(children: <Widget>[ Icon(Icons.change_history), Text('change_history') ],),
      Column(children: <Widget>[ Icon(Icons.chat), Text('chat') ],),
      Column(children: <Widget>[ Icon(Icons.chat_bubble), Text('chat_bubble') ],),
      Column(children: <Widget>[ Icon(Icons.chat_bubble_outline), Text('chat_bubble_outline') ],),
      Column(children: <Widget>[ Icon(Icons.check), Text('check') ],),

      Column(children: <Widget>[ Icon(Icons.check_box), Text('check_box') ],),
      Column(children: <Widget>[ Icon(Icons.check_box_outline_blank), Text('check_box_outline_blank') ],),
      Column(children: <Widget>[ Icon(Icons.check_circle), Text('check_circle') ],),
      Column(children: <Widget>[ Icon(Icons.check_circle_outline), Text('check_circle_outline') ],),
      Column(children: <Widget>[ Icon(Icons.chevron_left), Text('chevron_left') ],),
      Column(children: <Widget>[ Icon(Icons.chevron_right), Text('chevron_right') ],),

      Column(children: <Widget>[ Icon(Icons.child_care), Text('child_care') ],),
      Column(children: <Widget>[ Icon(Icons.child_friendly), Text('child_friendly') ],),
      Column(children: <Widget>[ Icon(Icons.chrome_reader_mode), Text('chrome_reader_mode') ],),
      Column(children: <Widget>[ Icon(Icons.class_), Text('class_') ],),
      Column(children: <Widget>[ Icon(Icons.clear), Text('clear') ],),
      Column(children: <Widget>[ Icon(Icons.clear_all), Text('clear_all') ],),

      Column(children: <Widget>[ Icon(Icons.close), Text('close') ],),
      Column(children: <Widget>[ Icon(Icons.closed_caption), Text('closed_caption') ],),
      Column(children: <Widget>[ Icon(Icons.cloud), Text('cloud') ],),
      Column(children: <Widget>[ Icon(Icons.cloud_circle), Text('cloud_circle') ],),
      Column(children: <Widget>[ Icon(Icons.cloud_done), Text('cloud_done') ],),
      Column(children: <Widget>[ Icon(Icons.cloud_download), Text('cloud_download') ],),

      Column(children: <Widget>[ Icon(Icons.cloud_off), Text('cloud_off') ],),
      Column(children: <Widget>[ Icon(Icons.cloud_queue), Text('cloud_queue') ],),
      Column(children: <Widget>[ Icon(Icons.cloud_upload), Text('cloud_upload') ],),
      Column(children: <Widget>[ Icon(Icons.code), Text('code') ],),
      Column(children: <Widget>[ Icon(Icons.collections), Text('collections') ],),
      Column(children: <Widget>[ Icon(Icons.collections_bookmark), Text('collections_bookmark') ],),

      Column(children: <Widget>[ Icon(Icons.color_lens), Text('color_lens') ],),
      Column(children: <Widget>[ Icon(Icons.colorize), Text('colorize') ],),
      Column(children: <Widget>[ Icon(Icons.comment), Text('comment') ],),
      Column(children: <Widget>[ Icon(Icons.compare), Text('compare') ],),
      Column(children: <Widget>[ Icon(Icons.compare_arrows), Text('compare_arrows') ],),
      Column(children: <Widget>[ Icon(Icons.computer), Text('computer') ],),

      Column(children: <Widget>[ Icon(Icons.confirmation_number), Text('confirmation_number') ],),
      Column(children: <Widget>[ Icon(Icons.contact_mail), Text('contact_mail') ],),
      Column(children: <Widget>[ Icon(Icons.contact_phone), Text('contact_phone') ],),
      Column(children: <Widget>[ Icon(Icons.contacts), Text('contacts') ],),
      Column(children: <Widget>[ Icon(Icons.content_copy), Text('content_copy') ],),
      Column(children: <Widget>[ Icon(Icons.content_cut), Text('content_cut') ],),

      Column(children: <Widget>[ Icon(Icons.content_paste), Text('content_paste') ],),
      Column(children: <Widget>[ Icon(Icons.control_point), Text('control_point') ],),
      Column(children: <Widget>[ Icon(Icons.control_point_duplicate), Text('control_point_duplicate') ],),
      Column(children: <Widget>[ Icon(Icons.copyright), Text('copyright') ],),
      Column(children: <Widget>[ Icon(Icons.create), Text('create') ],),
      Column(children: <Widget>[ Icon(Icons.create_new_folder), Text('create_new_folder') ],),

      Column(children: <Widget>[ Icon(Icons.credit_card), Text('credit_card') ],),
      Column(children: <Widget>[ Icon(Icons.crop), Text('crop') ],),
      Column(children: <Widget>[ Icon(Icons.crop_16_9), Text('crop_16_9') ],),
      Column(children: <Widget>[ Icon(Icons.crop_3_2), Text('crop_3_2') ],),
      Column(children: <Widget>[ Icon(Icons.crop_5_4), Text('crop_5_4') ],),
      Column(children: <Widget>[ Icon(Icons.crop_7_5), Text('crop_7_5') ],),

      Column(children: <Widget>[ Icon(Icons.crop_din), Text('crop_din') ],),
      Column(children: <Widget>[ Icon(Icons.crop_free), Text('crop_free') ],),
      Column(children: <Widget>[ Icon(Icons.crop_landscape), Text('crop_landscape') ],),
      Column(children: <Widget>[ Icon(Icons.crop_original), Text('crop_original') ],),
      Column(children: <Widget>[ Icon(Icons.crop_portrait), Text('crop_portrait') ],),
      Column(children: <Widget>[ Icon(Icons.crop_rotate), Text('crop_rotate') ],),

      Column(children: <Widget>[ Icon(Icons.crop_square), Text('crop_din') ],),
      Column(children: <Widget>[ Icon(Icons.dashboard), Text('dashboard') ],),
      Column(children: <Widget>[ Icon(Icons.data_usage), Text('data_usage') ],),
      Column(children: <Widget>[ Icon(Icons.date_range), Text('date_range') ],),
      Column(children: <Widget>[ Icon(Icons.dehaze), Text('dehaze') ],),
      Column(children: <Widget>[ Icon(Icons.delete), Text('delete') ],),

      Column(children: <Widget>[ Icon(Icons.delete_forever), Text('delete_forever') ],),
      Column(children: <Widget>[ Icon(Icons.delete_outline), Text('delete_outline') ],),
      Column(children: <Widget>[ Icon(Icons.delete_sweep), Text('delete_sweep') ],),
      Column(children: <Widget>[ Icon(Icons.departure_board), Text('departure_board') ],),
      Column(children: <Widget>[ Icon(Icons.description), Text('description') ],),
      Column(children: <Widget>[ Icon(Icons.desktop_mac), Text('desktop_mac') ],),

      Column(children: <Widget>[ Icon(Icons.desktop_windows), Text('desktop_windows') ],),
      Column(children: <Widget>[ Icon(Icons.details), Text('details') ],),
      Column(children: <Widget>[ Icon(Icons.developer_board), Text('developer_board') ],),
      Column(children: <Widget>[ Icon(Icons.developer_mode), Text('developer_mode') ],),
      Column(children: <Widget>[ Icon(Icons.device_hub), Text('device_hub') ],),
      Column(children: <Widget>[ Icon(Icons.device_unknown), Text('device_unknown') ],),

      Column(children: <Widget>[ Icon(Icons.devices), Text('devices') ],),
      Column(children: <Widget>[ Icon(Icons.devices_other), Text('devices_other') ],),
      Column(children: <Widget>[ Icon(Icons.dialer_sip), Text('dialer_sip') ],),
      Column(children: <Widget>[ Icon(Icons.dialpad), Text('dialpad') ],),
      Column(children: <Widget>[ Icon(Icons.directions), Text('directions') ],),
      Column(children: <Widget>[ Icon(Icons.directions_bike), Text('directions_bike') ],),

      Column(children: <Widget>[ Icon(Icons.directions_boat), Text('directions_boat') ],),
      Column(children: <Widget>[ Icon(Icons.directions_bus), Text('directions_bus') ],),
      Column(children: <Widget>[ Icon(Icons.directions_car), Text('directions_car') ],),
      Column(children: <Widget>[ Icon(Icons.directions_railway), Text('directions_railway') ],),
      Column(children: <Widget>[ Icon(Icons.directions_run), Text('directions_run') ],),
      Column(children: <Widget>[ Icon(Icons.directions_subway), Text('directions_subway') ],),

      Column(children: <Widget>[ Icon(Icons.directions_transit), Text('directions_transit') ],),
      Column(children: <Widget>[ Icon(Icons.directions_walk), Text('directions_walk') ],),
      Column(children: <Widget>[ Icon(Icons.disc_full), Text('disc_full') ],),
      Column(children: <Widget>[ Icon(Icons.dns), Text('dns') ],),
      Column(children: <Widget>[ Icon(Icons.do_not_disturb), Text('do_not_disturb') ],),
      Column(children: <Widget>[ Icon(Icons.do_not_disturb_alt), Text('do_not_disturb_alt') ],),

      Column(children: <Widget>[ Icon(Icons.do_not_disturb_off), Text('do_not_disturb_off') ],),
      Column(children: <Widget>[ Icon(Icons.do_not_disturb_on), Text('do_not_disturb_on') ],),
      Column(children: <Widget>[ Icon(Icons.dock), Text('dock') ],),
      Column(children: <Widget>[ Icon(Icons.domain), Text('domain') ],),
      Column(children: <Widget>[ Icon(Icons.done), Text('done') ],),
      Column(children: <Widget>[ Icon(Icons.done_all), Text('done_all') ],),

      Column(children: <Widget>[ Icon(Icons.done_outline), Text('done_outline') ],),
      Column(children: <Widget>[ Icon(Icons.donut_large), Text('donut_large') ],),
      Column(children: <Widget>[ Icon(Icons.donut_small), Text('donut_small') ],),
      Column(children: <Widget>[ Icon(Icons.drafts), Text('drafts') ],),
      Column(children: <Widget>[ Icon(Icons.drag_handle), Text('drag_handle') ],),
      Column(children: <Widget>[ Icon(Icons.drive_eta), Text('drive_eta') ],),

      Column(children: <Widget>[ Icon(Icons.dvr), Text('done_outline') ],),
      Column(children: <Widget>[ Icon(Icons.edit), Text('edit') ],),
      Column(children: <Widget>[ Icon(Icons.edit_attributes), Text('edit_attributes') ],),
      Column(children: <Widget>[ Icon(Icons.edit_location), Text('edit_location') ],),
      Column(children: <Widget>[ Icon(Icons.eject), Text('eject') ],),
      Column(children: <Widget>[ Icon(Icons.email), Text('email') ],),

      Column(children: <Widget>[ Icon(Icons.enhanced_encryption), Text('enhanced_encryption') ],),
      Column(children: <Widget>[ Icon(Icons.equalizer), Text('equalizer') ],),
      Column(children: <Widget>[ Icon(Icons.error), Text('error') ],),
      Column(children: <Widget>[ Icon(Icons.error_outline), Text('error_outline') ],),
      Column(children: <Widget>[ Icon(Icons.euro_symbol), Text('euro_symbol') ],),
      Column(children: <Widget>[ Icon(Icons.ev_station), Text('ev_station') ],),

      Column(children: <Widget>[ Icon(Icons.event), Text('event') ],),
      Column(children: <Widget>[ Icon(Icons.event_available), Text('event_available') ],),
      Column(children: <Widget>[ Icon(Icons.event_busy), Text('event_busy') ],),
      Column(children: <Widget>[ Icon(Icons.event_note), Text('event_note') ],),
      Column(children: <Widget>[ Icon(Icons.event_seat), Text('event_seat') ],),
      Column(children: <Widget>[ Icon(Icons.exit_to_app), Text('exit_to_app') ],),

      Column(children: <Widget>[ Icon(Icons.expand_less), Text('expand_less') ],),
      Column(children: <Widget>[ Icon(Icons.expand_more), Text('expand_more') ],),
      Column(children: <Widget>[ Icon(Icons.explicit), Text('explicit') ],),
      Column(children: <Widget>[ Icon(Icons.explore), Text('explore') ],),
      Column(children: <Widget>[ Icon(Icons.exposure), Text('exposure') ],),
      Column(children: <Widget>[ Icon(Icons.exposure_neg_1), Text('exposure_neg_1') ],),

      Column(children: <Widget>[ Icon(Icons.exposure_neg_2), Text('exposure_neg_2') ],),
      Column(children: <Widget>[ Icon(Icons.exposure_plus_1), Text('exposure_plus_1') ],),
      Column(children: <Widget>[ Icon(Icons.exposure_plus_2), Text('exposure_plus_2') ],),
      Column(children: <Widget>[ Icon(Icons.exposure_zero), Text('exposure_zero') ],),
      Column(children: <Widget>[ Icon(Icons.extension), Text('extension') ],),
      Column(children: <Widget>[ Icon(Icons.face), Text('face') ],),
    ],
  );

  @override
  Widget build (BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('material icon'),
      ),
      body: Container(
        padding: EdgeInsets.only(top: 20.0),
        child: iconListElement,
      ),
    );
  }
}